### ISSUE TITLE
EntityMap vs EntityArrayList

### ISSUE THREAD

**Issue by jLeeder1** [leederJosh/AlienAttack#11]
Currently there is a bug where killing an enemy means that their health is reduced to 0 and further bullets pass through them. They however do not despawn, and will still damage the player if walked over. 

I have found the reason for this: We are using a mix of the EntityMap and EntityArrayList in the EntityList class. The newer bullet system has it's collision and health reduction based around the list, but drawing and the melee system are using the EntityMap. I can fix this but would like consensus with which way to go so as to cause the least issues with other parts of the system.

**Comment by Sam-Robin** [comment]
Just add and take away from the map. The map updates constantly so that will always be the most up to date.
