### ISSUE TITLE
Pickup Handler

### ISSUE THREAD

**Issue by leederJosh** [leederJosh/AlienAttack#2]
The pickups handler will need to be passed around between many level objects. Is it better to pass them or create another singleton with the list of active pickups. Please advise

**Comment by NBatchelor1** [comment]
Singleton surely would be better since we don't want multiple pickup handlers in case they start to affect each other

**Comment by jLeeder1** [comment]
I got a version without a singleton that is able to spawn pickups (they don't have an effect as of yet) We'll need to give each level a handler or possibly put an object in the game class. I'll take a look at it now. Thanks for the help
