### ISSUE TITLE
Bullets affecting the player

### ISSUE THREAD

**Issue by leederJosh** [leederJosh/AlienAttack#3]
The bullets seem to be hitting the player, reducing health and despairing quickly. At the moment the system works by having a list of bullets and a list of entities. When a mouse click occurs bullet is created and added to the bullet list. It is given the position of the player plus extra on the X axis for now. The collision works by iterating through the bullet list and iterating through the entity list comparing the X and Y of each bullet against each entity. If they overlap the bullet should reduce health from that entity. However it only seems to hit the player.

Things I have tried to fix this:
-Using a normal for loop instead of an enhanced one to loop through entities, player is at index 0 so i tried starting from index 1
- An if statement that checks if the current entity is not a type player, if it is not a player the program moves into the collision detection code
- Spawning the bullet away from the player entirely (150 pixels away)

**Comment by Sam-Robin** [comment]
Let me help you with that in our next meeting.

**Comment by leederJosh** [comment]
Fixed this by only checking entities with an x position greater (or less than depending on direction) than the bullet. As before it was checking the bullet x against all players x and if their x was less than the bullets x the bullet despawned. This meant that entities to the left of the bullet would flag as true, despawning the bullet.

if (entity.getType().getId().equals("player") == false && entity.getx() > bullet.getBulletX())  in Shooting handler.
