### ISSUE TITLE
Current UI Moving

### ISSUE THREAD

**Issue by NBatchelor1** [leederJosh/AlienAttack#5]
The current UI we are using is being relocated on the screen when we resize the window, when made full screen the UI will disappear off the screen.

**Comment by jLeeder1** [comment]
This has been resolved now as we are using a fixed width screen. This has also fixed the grey line we were getting along the right of the screen. The fix was set in the AlienGame class where the Orthogonal camera is made. It has been set to "false" and been given a width and a height
